### ISSUE TITLE
Two offset?

### ISSUE THREAD

**Issue by kgahor** [katjahahn/JWScan#1]
Hi,

I am trying unpacking an Jar2Exe pack, I get this signatures:

Signatures found:
        \* Jar2Exe.com signature
        \* PZIP Magic Number (weak indication for embedded zip)

ZIP/Jar offsets: 0x..., 0x...

I tried dumping the first offset, and unzip the dump but I cannot. The second offset only contain jar2exe starter class. What is the solution for unpackking?

**Comment by struppigel** [comment]
This is no issue with the code of JWScan and as such the wrong place to discuss this. Maybe post your question in a Reverse Engineering related forum.
